#source components/common.sh
#
#CHECK_ROOT
#
#PRINT "Configure Yum Repo"
#curl -s -o /etc/yum.repos.d/mongodb.repo https://raw.githubusercontent.com/roboshop-devops-project/mongodb/main/mongo.repo &>>${LOG}
#CHECK_STAT $?
#
#PRINT "Install MongoDB"
#yum install -y mongodb-org &>>${LOG}
#CHECK_STAT $?
#
#PRINT "Configure MongoDB Service"
#sed -i -e 's/127.0.0.1/0.0.0.0/' /etc/mongod.conf
#CHECK_STAT $?
#
#PRINT "Start MongoDB"
#systemctl enable mongod &>>${LOG} && systemctl restart mongod &>>${LOG}
#CHECK_STAT $?
#
#PRINT "Download Schema"
#curl -s -L -o /tmp/mongodb.zip "https://github.com/roboshop-devops-project/mongodb/archive/main.zip" &>>${LOG}
#CHECK_STAT $?
#
#PRINT "Load Schema"
#cd /tmp && unzip -o mongodb.zip &>>${LOG} && cd mongodb-main && mongo < catalogue.js &>>${LOG} && mongo < users.js &>>${LOG}
#CHECK_STAT $?
#
- name: Copy Mongodb YUM repo file
  ansible.builtin.template:
    src: mongodb.repo
    dest: /etc/yum.repos.d/mongodb.repo

- name: Install MongoDB
  ansible.builtin.yum:
    name: mongodb-org
    state: installed

- name: Replace Listen address in MongoDB Configuration file
  ansible.builtin.replace:
    path: /etc/mongod.conf
    regexp: 127.0.0.1
    replace: 0.0.0.0

- name: Start MongoDB Service
  ansible.builtin.systemd:
    name: mongod
    enabled: yes
    state: restarted

- name: Download & Extract {{ COMPONENT }} Component Archive
  ansible.builtin.unarchive:
    src: https://github.com/roboshop-devops-project/{{ COMPONENT }}/archive/main.zip
    dest: /tmp
    remote_src: yes

- name: Load Schema
  community.mongodb.mongodb_shell:
    file: "/tmp/mongodb-main/{{item}}.js"
    idempotent: yes
  loop:
    - catalogue
    - users