#    PRINT "Download ${COMPONENT} content"
#    curl -s -L -o /tmp/${COMPONENT}.zip "https://github.com/roboshop-devops-project/${COMPONENT}/archive/main.zip" &>>${LOG}
#    CHECK_STAT $?
#
#    PRINT "Clean Old Content"
#    cd /usr/share/nginx/html
#    rm -rf * &>>${LOG}
#    CHECK_STAT $?
#
#    PRINT "Extract ${COMPONENT} Content"
#    unzip /tmp/${COMPONENT}.zip &>>${LOG}
#    CHECK_STAT $?
#
#    PRINT "Organise ${COMPONENT} Content"
#    mv ${COMPONENT}-main/* . && mv static/* . && rm -rf ${COMPONENT}-main README.md && mv localhost.conf /etc/nginx/default.d/roboshop.conf
#    CHECK_STAT $?
#
#    PRINT "Update ${COMPONENT} Configuration"
#    sed -i -e '/catalogue/ s/localhost/catalogue.roboshop.internal/' -e '/user/ s/localhost/user.roboshop.internal/' -e '/cart/ s/localhost/cart.roboshop.internal/' -e '/payment/ s/localhost/payment.roboshop.internal/' -e '/shipping/ s/localhost/shipping.roboshop.internal/' /etc/nginx/default.d/roboshop.conf
#    CHECK_STAT $?
#    # or using for loop
#    # for backend in catalogue cart user shipping payment ; do
#    # PRINT "Update Configuration for - $backend"
#    # sed -i -e "/$backend/ s/localhost/$backend.roboshop.internal/" /etc/nginx/default.d/roboshop.conf
#    # CHECK_STAT $?
#    # done
#
#    PRINT "Start Nginx Service"
#    systemctl enable nginx &>>${LOG} && systemctl restart nginx &>>${LOG}
#    CHECK_STAT $?
#  }

- name: Installing NGINX
  ansible.builtin.yum:
    name: nginx
    state: installed

# include another into my role i..e importing download from common to here
- name: Download {{ COMPONENT }} Code
  ansible.builtin.include_role:
    name: common
    tasks_from: download


