#source components/common.sh
#
#CHECK_ROOT
#
#if [ -z "${MYSQL_PASSWORD}" ]; then
#echo "export MYSQL_PASSWORD env variable"
#exit 1
#fi
#
#PRINT "Configure YUM Repos"
#curl -s -L -o /etc/yum.repos.d/mysql.repo https://raw.githubusercontent.com/roboshop-devops-project/mysql/main/mysql.repo &>>${LOG}
#CHECK_STAT $?
#
#PRINT "Install MySql"
#yum install mysql-community-server -y &>>${LOG}
#systemctl enable mysqld &>>${LOG} && systemctl start mysqld &>>${LOG}
#CHECK_STAT $?
#
#MYSQL_DEFAULT_PASSWORD=$(grep 'temporary password' /var/log/mysqld.log | awk '{print $NF}')
#
#echo show databases | mysql -uroot -p"${MYSQL_PASSWORD}" &>>${LOG}
#if [ $? -ne 0 ]; then
#PRINT "RESET Root Password"
#echo "ALTER USER 'root'@'localhost' IDENTIFIED BY '${MYSQL_PASSWORD}';" | mysql --connect-expired-password -uroot -p"${MYSQL_DEFAULT_PASSWORD}"  &>>${LOG}
#CHECK_STAT $?
#fi
#
#echo show plugins | mysql -uroot -p"${MYSQL_PASSWORD}" 2>>${LOG} | grep validate_password &>>${LOG}
#if [ $? -eq 0 ]; then
#PRINT "Uninstall Password Validate Plugin"
#echo "uninstall plugin validate_password;" | mysql -uroot -p"${MYSQL_PASSWORD}" &>>${LOG}
#CHECK_STAT $?
#fi
#
#PRINT "Download Schema"
#curl -s -L -o /tmp/mysql.zip "https://github.com/roboshop-devops-project/mysql/archive/main.zip" &>>${LOG}
#CHECK_STAT $?
#
#PRINT "Load Schema"
#cd /tmp && unzip -o mysql.zip &>>${LOG} && cd mysql-main && mysql -u root -p"${MYSQL_PASSWORD}" <shipping.sql &>>${LOG}
#CHECK_STAT $?

- name: Fail if the Password MYSQL_PASSWORD doesnot exist
  ansible.builtin.fail:
    msg: MYSQL_PASSWORD variable is missing
  when: MYSQL_PASSWORD is undefined

- name: Copy MYSQL Repo File
  ansible.builtin.template:
    src: mysql.repo
    dest: /etc/yum.repos.d/mysql.repo

- name: Install MySQL Server
  ansible.builtin.yum:
    name:
      - mysql-community-server
      - MySQL-python
    state: installed

- name: Start MySQL Service
  ansible.builtin.systemd:
    name: mysqld
    state: started
    enabled: yes

- name: Fetch MySQL Log File
  ansible.builtin.slurp:
    src: /var/log/mysqld.log
  register: mysql_log

- name: Fetch Password from MySQL Log File
  ansible.builtin.set_fact:
    DEFAULT_PASSWORD: "{{mysql_log['content'] | b64decode | regex_findall('.*temporary password.*') | join (' ')| split(' ') | last}}"

- name: Check MySQL Password has been reset or not
  community.mysql.mysql_info:
    login_user: root
    login_password: "{{MYSQL_PASSWORD}}"
    filter: version
  ignore_errors: yes
  register: mysql_conn

- name: Reset MySQL Password
  ansible.builtin.shell: echo "ALTER USER 'root'@'localhost' IDENTIFIED BY '{{MYSQL_PASSWORD}}';" | mysql --connect-expired-password -uroot
   -p"{{DEFAULT_PASSWORD}}"
  when: mysql_conn is failed

- name: Check Validate Password Plugin
  ansible.builtin.shell: echo show plugins | mysql -uroot -p"{{MYSQL_PASSWORD}}" | grep validate_password
  register: plugin_info
  ignore_errors: yes

- name: Remove Validate Password Plugin
  ansible.builtin.shell: echo "uninstall plugin validate_password;" | mysql -uroot -p"{{MYSQL_PASSWORD}}"
  when: plugin_info is succeeded

- name: Download & Extract {{ COMPONENT }} Component Archive
  ansible.builtin.unarchive:
    src: https://github.com/roboshop-devops-project/{{ COMPONENT }}/archive/main.zip
    dest: /tmp
    remote_src: yes

- name: Load Schema
  community.mysql.mysql_db:
    state: import
    name: all
    target: /tmp/mysql-main/shipping.sql
    login_user: root
    login_password: "{{MYSQL_PASSWORD}}"
