#    PRINT "Install Nodejs Dependencies for ${COMPONENT} Component"
#    mv ${COMPONENT}-main ${COMPONENT} && cd ${COMPONENT} && npm install &>>${LOG}
#    CHECK_STAT $?
#
#    SYSTEMD

- name: Setup YUM repos for NodeJS
  ansible.builtin.shell: curl --silent --location https://rpm.nodesource.com/setup_16.x | sudo bash

- name: Install NodeJS
  ansible.builtin.yum:
    name: nodejs
    state: installed

- name: Import Common App Setup Configuration
  ansible.builtin.include_role:
    name: common
    tasks_from: download

- name: Install Nodejs Dependencies
  community.general.npm:
   path: "{{ APP_LOCATION }}"

- name: SystemD Setup for {{ COMPONENT }} Service
  ansible.builtin.include_role:
    name: common
    tasks_from: systemd

